rasp:
    resource: "@RaspBundle/Resources/config/routing.yml"
    prefix:   /rasp

files_images:
    resource: "@FilesImagesBundle/Resources/config/routing.yml"
    prefix:   /

admin_panel:
    resource: "@AdminPanelBundle/Resources/config/routing.yml"
    prefix:   /admin

blog_blog:
    resource: "@BlogPublicationsBundle/Resources/config/routing.yml"
    prefix:   /

profile_user:
    resource: "@ProfileUserBundle/Resources/config/routing.yml"
    prefix:   /

used:
    resource: "@AutoUsedBundle/Resources/config/routing.yml"
    prefix:   /

auto_catalog:
    resource: "@AutoCatalogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

vkontakte_login:
    pattern: /login/check-vkontakte