<?php

namespace Auto\UsedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MostParsedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MostParsedRepository extends EntityRepository
{
    public function findOne()
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->setFirstResult(0)
            ->setMaxResults(1)
            ->where('p.isParsed = 0')
            ->orderBy('p.id', 'desc');
        return $query->getQuery()->getSingleResult();
    }
}
