<?php

namespace Auto\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function getPopularBrands()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AutoCatalogBundle:Brand p WHERE p.popular = true ORDER BY p.name ASC'
            )
            ->getResult();
    }

    public function getUnpopularBrands()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AutoCatalogBundle:Brand p WHERE p.popular = false ORDER BY p.name ASC'
            )
            ->getResult();
    }

    public function getAvgFilling()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT AVG(p.filling)  FROM AutoCatalogBundle:Brand p'
            )
            ->getOneOrNullResult();
    }
}
