<?php

namespace Auto\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends EntityRepository
{
    public function getAvgFilling()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT AVG(p.filling)  FROM AutoCatalogBundle:Model p'
            )
            ->getOneOrNullResult();
    }
}
