auto_used_index:
    path:     /automobili
    defaults: { _controller: AutoUsedBundle:Default:index }

auto_used_add:
    path:     /automobili/novoe-objavlenie
    defaults: { _controller: AutoUsedBundle:Default:add }

auto_used_parser_parse_list:
    path: /parser/get-parse-list
    defaults: { _controller: AutoUsedBundle:Parser:parselist }

auto_used_parser_parse_ad:
    path: /parser/parse-ad
    defaults: { _controller: AutoUsedBundle:Parser:parsead }

auto_used_ajax_ads:
    path: /auto/used/ajax/refresh
    defaults: { _controller: AutoUsedBundle:Ajax:refreshAds}

auto_used_ajax_count:
    path: /auto/used/ajax/count
    defaults: { _controller: AutoUsedBundle:Ajax:count }

auto_used_default_car:
    path: /automobili/{id}
    defaults: { _controller: AutoUsedBundle:Default:car }
    requirements:
        id:  \d+

auto_used_count_new_ads:
    path: /auto/used/ajax/count-new-ads
    defaults: { _controller: AutoUsedBundle:Ajax:countNewAds }