auto_used_index:
    path:     /automobili
    defaults: { _controller: AutoUsedBundle:Default:index }

auto_used_parser_parse_list:
    path: /parser/get-parse-list
    defaults: { _controller: AutoUsedBundle:Parser:parselist }

auto_used_parser_parse_ad:
    path: /parser/parse-ad
    defaults: { _controller: AutoUsedBundle:Parser:parsead }
